<?php

namespace Inventas\AppStoreConnectKit\Api\Dto;

/**
 * AppVersionState
 */
enum AppVersionState: string
{
    case ACCEPTED = 'ACCEPTED';
    case DEVELOPER_REJECTED = 'DEVELOPER_REJECTED';
    case IN_REVIEW = 'IN_REVIEW';
    case INVALID_BINARY = 'INVALID_BINARY';
    case METADATA_REJECTED = 'METADATA_REJECTED';
    case PENDING_APPLE_RELEASE = 'PENDING_APPLE_RELEASE';
    case PENDING_DEVELOPER_RELEASE = 'PENDING_DEVELOPER_RELEASE';
    case PREPARE_FOR_SUBMISSION = 'PREPARE_FOR_SUBMISSION';
    case PROCESSING_FOR_DISTRIBUTION = 'PROCESSING_FOR_DISTRIBUTION';
    case READY_FOR_DISTRIBUTION = 'READY_FOR_DISTRIBUTION';
    case READY_FOR_REVIEW = 'READY_FOR_REVIEW';
    case REJECTED = 'REJECTED';
    case REPLACED_WITH_NEW_VERSION = 'REPLACED_WITH_NEW_VERSION';
    case WAITING_FOR_EXPORT_COMPLIANCE = 'WAITING_FOR_EXPORT_COMPLIANCE';
    case WAITING_FOR_REVIEW = 'WAITING_FOR_REVIEW';
}
