<?php

namespace Inventas\AppStoreConnectKit\Api\Dto;

/**
 * CapabilityType
 */
enum CapabilityType: string
{
    case ICLOUD = 'ICLOUD';
    case IN_APP_PURCHASE = 'IN_APP_PURCHASE';
    case GAME_CENTER = 'GAME_CENTER';
    case PUSH_NOTIFICATIONS = 'PUSH_NOTIFICATIONS';
    case WALLET = 'WALLET';
    case INTER_APP_AUDIO = 'INTER_APP_AUDIO';
    case MAPS = 'MAPS';
    case ASSOCIATED_DOMAINS = 'ASSOCIATED_DOMAINS';
    case PERSONAL_VPN = 'PERSONAL_VPN';
    case APP_GROUPS = 'APP_GROUPS';
    case HEALTHKIT = 'HEALTHKIT';
    case HOMEKIT = 'HOMEKIT';
    case WIRELESS_ACCESSORY_CONFIGURATION = 'WIRELESS_ACCESSORY_CONFIGURATION';
    case APPLE_PAY = 'APPLE_PAY';
    case DATA_PROTECTION = 'DATA_PROTECTION';
    case SIRIKIT = 'SIRIKIT';
    case NETWORK_EXTENSIONS = 'NETWORK_EXTENSIONS';
    case MULTIPATH = 'MULTIPATH';
    case HOT_SPOT = 'HOT_SPOT';
    case NFC_TAG_READING = 'NFC_TAG_READING';
    case CLASSKIT = 'CLASSKIT';
    case AUTOFILL_CREDENTIAL_PROVIDER = 'AUTOFILL_CREDENTIAL_PROVIDER';
    case ACCESS_WIFI_INFORMATION = 'ACCESS_WIFI_INFORMATION';
    case NETWORK_CUSTOM_PROTOCOL = 'NETWORK_CUSTOM_PROTOCOL';
    case COREMEDIA_HLS_LOW_LATENCY = 'COREMEDIA_HLS_LOW_LATENCY';
    case SYSTEM_EXTENSION_INSTALL = 'SYSTEM_EXTENSION_INSTALL';
    case USER_MANAGEMENT = 'USER_MANAGEMENT';
    case APPLE_ID_AUTH = 'APPLE_ID_AUTH';
}
