<?php

namespace Inventas\AppStoreConnectKit\Api\Dto;

/**
 * CertificateType
 */
enum CertificateType: string
{
    case APPLE_PAY = 'APPLE_PAY';
    case APPLE_PAY_MERCHANT_IDENTITY = 'APPLE_PAY_MERCHANT_IDENTITY';
    case APPLE_PAY_PSP_IDENTITY = 'APPLE_PAY_PSP_IDENTITY';
    case APPLE_PAY_RSA = 'APPLE_PAY_RSA';
    case DEVELOPER_ID_KEXT = 'DEVELOPER_ID_KEXT';
    case DEVELOPER_ID_KEXT_G2 = 'DEVELOPER_ID_KEXT_G2';
    case DEVELOPER_ID_APPLICATION = 'DEVELOPER_ID_APPLICATION';
    case DEVELOPER_ID_APPLICATION_G2 = 'DEVELOPER_ID_APPLICATION_G2';
    case DEVELOPMENT = 'DEVELOPMENT';
    case DISTRIBUTION = 'DISTRIBUTION';
    case IDENTITY_ACCESS = 'IDENTITY_ACCESS';
    case IOS_DEVELOPMENT = 'IOS_DEVELOPMENT';
    case IOS_DISTRIBUTION = 'IOS_DISTRIBUTION';
    case MAC_APP_DISTRIBUTION = 'MAC_APP_DISTRIBUTION';
    case MAC_INSTALLER_DISTRIBUTION = 'MAC_INSTALLER_DISTRIBUTION';
    case MAC_APP_DEVELOPMENT = 'MAC_APP_DEVELOPMENT';
    case PASS_TYPE_ID = 'PASS_TYPE_ID';
    case PASS_TYPE_ID_WITH_NFC = 'PASS_TYPE_ID_WITH_NFC';
}
