<?php

namespace Inventas\AppStoreConnectKit\Api\Dto;

/**
 * ExternalBetaState
 */
enum ExternalBetaState: string
{
    case PROCESSING = 'PROCESSING';
    case PROCESSING_EXCEPTION = 'PROCESSING_EXCEPTION';
    case MISSING_EXPORT_COMPLIANCE = 'MISSING_EXPORT_COMPLIANCE';
    case READY_FOR_BETA_TESTING = 'READY_FOR_BETA_TESTING';
    case IN_BETA_TESTING = 'IN_BETA_TESTING';
    case EXPIRED = 'EXPIRED';
    case READY_FOR_BETA_SUBMISSION = 'READY_FOR_BETA_SUBMISSION';
    case IN_EXPORT_COMPLIANCE_REVIEW = 'IN_EXPORT_COMPLIANCE_REVIEW';
    case WAITING_FOR_BETA_REVIEW = 'WAITING_FOR_BETA_REVIEW';
    case IN_BETA_REVIEW = 'IN_BETA_REVIEW';
    case BETA_REJECTED = 'BETA_REJECTED';
    case BETA_APPROVED = 'BETA_APPROVED';
    case NOT_APPLICABLE = 'NOT_APPLICABLE';
}
