<?php

namespace Inventas\AppStoreConnectKit\Api\Dto;

/**
 * GameCenterLeaderboardFormatter
 */
enum GameCenterLeaderboardFormatter: string
{
    case INTEGER = 'INTEGER';
    case DECIMAL_POINT_1_PLACE = 'DECIMAL_POINT_1_PLACE';
    case DECIMAL_POINT_2_PLACE = 'DECIMAL_POINT_2_PLACE';
    case DECIMAL_POINT_3_PLACE = 'DECIMAL_POINT_3_PLACE';
    case ELAPSED_TIME_CENTISECOND = 'ELAPSED_TIME_CENTISECOND';
    case ELAPSED_TIME_MINUTE = 'ELAPSED_TIME_MINUTE';
    case ELAPSED_TIME_SECOND = 'ELAPSED_TIME_SECOND';
    case MONEY_POUND_DECIMAL = 'MONEY_POUND_DECIMAL';
    case MONEY_POUND = 'MONEY_POUND';
    case MONEY_DOLLAR_DECIMAL = 'MONEY_DOLLAR_DECIMAL';
    case MONEY_DOLLAR = 'MONEY_DOLLAR';
    case MONEY_EURO_DECIMAL = 'MONEY_EURO_DECIMAL';
    case MONEY_EURO = 'MONEY_EURO';
    case MONEY_FRANC_DECIMAL = 'MONEY_FRANC_DECIMAL';
    case MONEY_FRANC = 'MONEY_FRANC';
    case MONEY_KRONER_DECIMAL = 'MONEY_KRONER_DECIMAL';
    case MONEY_KRONER = 'MONEY_KRONER';
    case MONEY_YEN = 'MONEY_YEN';
}
