<?php

namespace Inventas\AppStoreConnectKit\Api\Dto;

/**
 * InAppPurchaseState
 */
enum InAppPurchaseState: string
{
    case MISSING_METADATA = 'MISSING_METADATA';
    case WAITING_FOR_UPLOAD = 'WAITING_FOR_UPLOAD';
    case PROCESSING_CONTENT = 'PROCESSING_CONTENT';
    case READY_TO_SUBMIT = 'READY_TO_SUBMIT';
    case WAITING_FOR_REVIEW = 'WAITING_FOR_REVIEW';
    case IN_REVIEW = 'IN_REVIEW';
    case DEVELOPER_ACTION_NEEDED = 'DEVELOPER_ACTION_NEEDED';
    case PENDING_BINARY_APPROVAL = 'PENDING_BINARY_APPROVAL';
    case APPROVED = 'APPROVED';
    case DEVELOPER_REMOVED_FROM_SALE = 'DEVELOPER_REMOVED_FROM_SALE';
    case REMOVED_FROM_SALE = 'REMOVED_FROM_SALE';
    case REJECTED = 'REJECTED';
}
