<?php

namespace Inventas\AppStoreConnectKit\Api\Dto;

/**
 * ScreenshotDisplayType
 */
enum ScreenshotDisplayType: string
{
    case APP_IPHONE_67 = 'APP_IPHONE_67';
    case APP_IPHONE_61 = 'APP_IPHONE_61';
    case APP_IPHONE_65 = 'APP_IPHONE_65';
    case APP_IPHONE_58 = 'APP_IPHONE_58';
    case APP_IPHONE_55 = 'APP_IPHONE_55';
    case APP_IPHONE_47 = 'APP_IPHONE_47';
    case APP_IPHONE_40 = 'APP_IPHONE_40';
    case APP_IPHONE_35 = 'APP_IPHONE_35';
    case APP_IPAD_PRO_3GEN_129 = 'APP_IPAD_PRO_3GEN_129';
    case APP_IPAD_PRO_3GEN_11 = 'APP_IPAD_PRO_3GEN_11';
    case APP_IPAD_PRO_129 = 'APP_IPAD_PRO_129';
    case APP_IPAD_105 = 'APP_IPAD_105';
    case APP_IPAD_97 = 'APP_IPAD_97';
    case APP_DESKTOP = 'APP_DESKTOP';
    case APP_WATCH_ULTRA = 'APP_WATCH_ULTRA';
    case APP_WATCH_SERIES_10 = 'APP_WATCH_SERIES_10';
    case APP_WATCH_SERIES_7 = 'APP_WATCH_SERIES_7';
    case APP_WATCH_SERIES_4 = 'APP_WATCH_SERIES_4';
    case APP_WATCH_SERIES_3 = 'APP_WATCH_SERIES_3';
    case APP_APPLE_TV = 'APP_APPLE_TV';
    case APP_APPLE_VISION_PRO = 'APP_APPLE_VISION_PRO';
    case IMESSAGE_APP_IPHONE_67 = 'IMESSAGE_APP_IPHONE_67';
    case IMESSAGE_APP_IPHONE_61 = 'IMESSAGE_APP_IPHONE_61';
    case IMESSAGE_APP_IPHONE_65 = 'IMESSAGE_APP_IPHONE_65';
    case IMESSAGE_APP_IPHONE_58 = 'IMESSAGE_APP_IPHONE_58';
    case IMESSAGE_APP_IPHONE_55 = 'IMESSAGE_APP_IPHONE_55';
    case IMESSAGE_APP_IPHONE_47 = 'IMESSAGE_APP_IPHONE_47';
    case IMESSAGE_APP_IPHONE_40 = 'IMESSAGE_APP_IPHONE_40';
    case IMESSAGE_APP_IPAD_PRO_3GEN_129 = 'IMESSAGE_APP_IPAD_PRO_3GEN_129';
    case IMESSAGE_APP_IPAD_PRO_3GEN_11 = 'IMESSAGE_APP_IPAD_PRO_3GEN_11';
    case IMESSAGE_APP_IPAD_PRO_129 = 'IMESSAGE_APP_IPAD_PRO_129';
    case IMESSAGE_APP_IPAD_105 = 'IMESSAGE_APP_IPAD_105';
    case IMESSAGE_APP_IPAD_97 = 'IMESSAGE_APP_IPAD_97';
}
