<?php

namespace Inventas\AppStoreConnectKit\Api\Dto;

/**
 * WebhookEventType
 */
enum WebhookEventType: string
{
    case ALTERNATIVE_DISTRIBUTION_PACKAGE_AVAILABLE_UPDATED = 'ALTERNATIVE_DISTRIBUTION_PACKAGE_AVAILABLE_UPDATED';
    case ALTERNATIVE_DISTRIBUTION_PACKAGE_VERSION_CREATED = 'ALTERNATIVE_DISTRIBUTION_PACKAGE_VERSION_CREATED';
    case ALTERNATIVE_DISTRIBUTION_TERRITORY_AVAILABILITY_UPDATED = 'ALTERNATIVE_DISTRIBUTION_TERRITORY_AVAILABILITY_UPDATED';
    case APP_STORE_VERSION_APP_VERSION_STATE_UPDATED = 'APP_STORE_VERSION_APP_VERSION_STATE_UPDATED';
    case BACKGROUND_ASSET_VERSION_APP_STORE_RELEASE_STATE_UPDATED = 'BACKGROUND_ASSET_VERSION_APP_STORE_RELEASE_STATE_UPDATED';
    case BACKGROUND_ASSET_VERSION_EXTERNAL_BETA_RELEASE_STATE_UPDATED = 'BACKGROUND_ASSET_VERSION_EXTERNAL_BETA_RELEASE_STATE_UPDATED';
    case BACKGROUND_ASSET_VERSION_INTERNAL_BETA_RELEASE_CREATED = 'BACKGROUND_ASSET_VERSION_INTERNAL_BETA_RELEASE_CREATED';
    case BACKGROUND_ASSET_VERSION_STATE_UPDATED = 'BACKGROUND_ASSET_VERSION_STATE_UPDATED';
    case BETA_FEEDBACK_CRASH_SUBMISSION_CREATED = 'BETA_FEEDBACK_CRASH_SUBMISSION_CREATED';
    case BETA_FEEDBACK_SCREENSHOT_SUBMISSION_CREATED = 'BETA_FEEDBACK_SCREENSHOT_SUBMISSION_CREATED';
    case BUILD_BETA_DETAIL_EXTERNAL_BUILD_STATE_UPDATED = 'BUILD_BETA_DETAIL_EXTERNAL_BUILD_STATE_UPDATED';
    case BUILD_UPLOAD_STATE_UPDATED = 'BUILD_UPLOAD_STATE_UPDATED';
}
